!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 200.0
  P2: 400.0
  correlation_window_size: 23
  disp12MaxDiff: 0
  disparity_range: 96
  fullDP: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 200.0
      P2: 400.0
      correlation_window_size: 23
      disp12MaxDiff: 0
      disparity_range: 96
      fullDP: false
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: -97
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 57
      prefilter_size: 9
      speckle_range: 1
      speckle_size: 466
      state: true
      stereo_algorithm: 0
      texture_threshold: 10
      type: ''
      uniqueness_ratio: 27.0
    state: []
  min_disparity: -97
  prefilter_cap: 57
  prefilter_size: 9
  speckle_range: 1
  speckle_size: 466
  stereo_algorithm: 0
  texture_threshold: 10
  uniqueness_ratio: 27.0
state: []
